linters:
  enable-all: true  
  disable:
    - depguard
    - tenv
    - forbidigo
    - nlreturn

linters-settings:
  varnamelen:
    min-name-length: 2

  govet:
    enable-all: true

  gci:
    sections:
      - standard
      - default      
      - prefix(github.com/mch735/education/work2)
    skip-generated: true
