linters:
  enable-all: true  
  disable:
    - depguard
    - tenv
    - exhaustruct
    - forbidigo
    - nilnil

linters-settings:
  varnamelen:
    min-name-length: 1

  govet:
    enable-all: true

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mch735/education/work5)
    skip-generated: true   

  tagliatelle:
    case:
      rules:
        json: snake
        env: upperSnake

  lll:
    line-length: 140