version: '3.9'

services:
  db:
    image: postgres:17-alpine    
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    env_file: .env
    command: redis-server --save "" --appendonly no 
    ports:
      - 6379:6379

  nats:
    image: nats:2.11-alpine
    restart: always
    env_file: .env
    ports:
      - 8222:8222
      - 6222:6222
      - 4222:4222
